name: Tests

on: [push]

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "test with ${{ matrix.py }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: "Install poetry"
        run: python -m pip install poetry==1.5.1
      - name: "Install tox"
        run: python -m pip install tox-gh>=1.2

      - name: "Setup test suite"
        run: tox -vv --notest

      - name: "Run test suite"
        run: tox --skip-pkg-install
